CREATE TABLE
  transformed_files._01_NOVA_TABELA_LIGUE180_2019_A_2023T1 AS
WITH
  ligue180_s2_2020 AS (
  SELECT
    Datadecadastro,
    Canaldeatendimento,
    Denunciaemergencial,
    Denunciante,
    Cenariodaviolacao,
    Pais,
    UF,
    Municipio,
    Frequencia,
    Iniciodasviolacoes,
    sl_quantidade_vitimas,
    Grupovulneravel,
    Motivacao,
    Relacaovitimasuspeito,
    sl_vitima_cadastro,
    Sexodavitima,
    Orientacaosexualdavitima,
    Faixaetariadavitima,
    Nacionalidadedavitima,
    sl_vitima_naturalidade,
    sl_vitima_naturalizado_uf,
    sl_vitima_naturalizado_municipio,
    Deficienciadavitima,
    Doencararadavitima,
    Deficienciarelacionadaadoencarara,
    Vitimapresoa,
    Paisdavitima,
    UFdavitima,
    Municipiodavitima,
    Profissaodavitima,
    Graudeinstrucaodavitima,
    Religiaodavitima,
    RacaCordavitima,
    Etniadavitima,
    Faixaderendadavitima,
    NaturezaJuridicadoSuspeito,
    Sexodosuspeito,
    Orientacaosexualdosuspeito,
    Faixaetariadosuspeito,
    Suspeitonacionalidade,
    sl_suspeito_naturalidade,
    sl_suspeito_naturalizado_uf,
    sl_suspeito_naturalizado_municipio,
    Deficienciadosuspeito,
    Doencararadosuspeito,
    Deficienciarelacionadaadoencararasuspeito,
    Suspeitopreso,
    Paisdosuspeito,
    UFdosuspeito,
    sl_suspeito_municipio,
    Profissaodosuspeito,
    Graudeinstrucaodosuspeito,
    Religiaodosuspeito,
    RacaCordosuspeito,
    SuspeitoEtnia,
    Faixaderendadosuspeito,
    VinculoOrgaoPJdosuspeito,
    sl_suspeito_ramo,
    suspeito_especificacao_etnia,
    vitima_especificacao_etnia,
    violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_S2_2020 ),
  ligue180_s1_2021 AS (
  SELECT
    Datadecadastro,
    Canaldeatendimento,
    Denunciaemergencial,
    Denunciante,
    Cenariodaviolacao,
    Pais,
    UF,
    Municipio,
    Frequencia,
    Iniciodasviolacoes,
    sl_quantidade_vitimas,
    Grupovulneravel,
    Motivacao,
    Relacaovitimasuspeito,
    sl_vitima_cadastro,
    Sexodavitima,
    Orientacaosexualdavitima,
    Faixaetariadavitima,
    Nacionalidadedavitima,
    sl_vitima_naturalidade,
    sl_vitima_naturalizado_uf,
    sl_vitima_naturalizado_municipio,
    Deficienciadavitima,
    Doencararadavitima,
    Deficienciarelacionadaadoencarara,
    Vitimapresoa,
    Paisdavitima,
    UFdavitima,
    Municipiodavitima,
    Profissaodavitima,
    Graudeinstrucaodavitima,
    Religiaodavitima,
    RacaCordavitima,
    Etniadavitima,
    Faixaderendadavitima,
    NaturezaJuridicadoSuspeito,
    Sexodosuspeito,
    Orientacaosexualdosuspeito,
    Faixaetariadosuspeito,
    Suspeitonacionalidade,
    sl_suspeito_naturalidade,
    sl_suspeito_naturalizado_uf,
    sl_suspeito_naturalizado_municipio,
    Deficienciadosuspeito,
    Doencararadosuspeito,
    Deficienciarelacionadaadoencararasuspeito,
    Suspeitopreso,
    Paisdosuspeito,
    UFdosuspeito,
    sl_suspeito_municipio,
    Profissaodosuspeito,
    Graudeinstrucaodosuspeito,
    Religiaodosuspeito,
    RacaCordosuspeito,
    SuspeitoEtnia,
    Faixaderendadosuspeito,
    VinculoOrgaoPJdosuspeito,
    sl_suspeito_ramo,
    suspeito_especificacao_etnia,
    vitima_especificacao_etnia,
    violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_S1_2021 ),
  ligue180_s2_2021 AS (
  SELECT
    Datadecadastro,
    Canaldeatendimento,
    Denunciaemergencial,
    Denunciante,
    Cenariodaviolacao,
    Pais,
    UF,
    Municipio,
    Frequencia,
    Iniciodasviolacoes,
    sl_quantidade_vitimas,
    Grupovulneravel,
    Motivacao,
    Relacaovitimasuspeito,
    sl_vitima_cadastro,
    Sexodavitima,
    Orientacaosexualdavitima,
    Faixaetariadavitima,
    Nacionalidadedavitima,
    sl_vitima_naturalidade,
    sl_vitima_naturalizado_uf,
    sl_vitima_naturalizado_municipio,
    Deficienciadavitima,
    Doencararadavitima,
    Deficienciarelacionadaadoencarara,
    Vitimapresoa,
    Paisdavitima,
    UFdavitima,
    Municipiodavitima,
    Profissaodavitima,
    Graudeinstrucaodavitima,
    Religiaodavitima,
    RacaCordavitima,
    Etniadavitima,
    Faixaderendadavitima,
    NaturezaJuridicadoSuspeito,
    Sexodosuspeito,
    Orientacaosexualdosuspeito,
    Faixaetariadosuspeito,
    Suspeitonacionalidade,
    sl_suspeito_naturalidade,
    sl_suspeito_naturalizado_uf,
    sl_suspeito_naturalizado_municipio,
    Deficienciadosuspeito,
    Doencararadosuspeito,
    Deficienciarelacionadaadoencararasuspeito,
    Suspeitopreso,
    Paisdosuspeito,
    UFdosuspeito,
    sl_suspeito_municipio,
    Profissaodosuspeito,
    Graudeinstrucaodosuspeito,
    Religiaodosuspeito,
    RacaCordosuspeito,
    SuspeitoEtnia,
    Faixaderendadosuspeito,
    VinculoOrgaoPJdosuspeito,
    sl_suspeito_ramo,
    suspeito_especificacao_etnia,
    vitima_especificacao_etnia,
    violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_S2_2021 ),
  ligue180_s1_2022 AS (
  SELECT
    Datadecadastro,
    Canaldeatendimento,
    Denunciaemergencial,
    Denunciante,
    Cenariodaviolacao,
    Pais,
    UF,
    Municipio,
    Frequencia,
    Iniciodasviolacoes,
    sl_quantidade_vitimas,
    Grupovulneravel,
    Motivacao,
    Relacaovitimasuspeito,
    sl_vitima_cadastro,
    Sexodavitima,
    Orientacaosexualdavitima,
    Faixaetariadavitima,
    Nacionalidadedavitima,
    sl_vitima_naturalidade,
    sl_vitima_naturalizado_uf,
    sl_vitima_naturalizado_municipio,
    Deficienciadavitima,
    Doencararadavitima,
    Deficienciarelacionadaadoencarara,
    Vitimapresoa,
    Paisdavitima,
    UFdavitima,
    Municipiodavitima,
    Profissaodavitima,
    Graudeinstrucaodavitima,
    Religiaodavitima,
    RacaCordavitima,
    Etniadavitima,
    Faixaderendadavitima,
    NaturezaJuridicadoSuspeito,
    Sexodosuspeito,
    Orientacaosexualdosuspeito,
    Faixaetariadosuspeito,
    Suspeitonacionalidade,
    sl_suspeito_naturalidade,
    sl_suspeito_naturalizado_uf,
    sl_suspeito_naturalizado_municipio,
    Deficienciadosuspeito,
    Doencararadosuspeito,
    Deficienciarelacionadaadoencararasuspeito,
    Suspeitopreso,
    Paisdosuspeito,
    UFdosuspeito,
    sl_suspeito_municipio,
    Profissaodosuspeito,
    Graudeinstrucaodosuspeito,
    Religiaodosuspeito,
    RacaCordosuspeito,
    SuspeitoEtnia,
    Faixaderendadosuspeito,
    VinculoOrgaoPJdosuspeito,
    sl_suspeito_ramo,
    suspeito_especificacao_etnia,
    vitima_especificacao_etnia,
    violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_S1_2022 ),
  ligue180_s2_2022 AS (
  SELECT
    Data_de_cadastro,
    Canal_de_atendimento,
    Denuncia_emergencial,
    Denunciante,
    Cenario_da_violacao,
    Pais,
    UF,
    Municipio,
    Frequencia,
    Inicio_das_violacoes,
    sl_quantidade_vitimas,
    Grupo_vulneravel,
    Motivacao,
    Relacao_vitima_suspeito,
    sl_vitima_cadastro,
    Sexo_da_vitima,
    Orientacao_sexual_da_vitima,
    Faixa_etaria_da_vitima,
    Nacionalidade_da_vitima,
    sl_vitima_naturalidade,
    sl_vitima_naturalizado_uf,
    sl_vitima_naturalizado_municipio,
    Deficiencia_da_vitima,
    Doenca_rara_da_vitima,
    Deficiencia_relacionada_a_doenca_rara,
    Vitima_preso_a,
    Pais_da_vitima,
    UF_da_vitima,
    Municipio_da_vitima,
    Profissao_da_vitima,
    Grau_de_instrucao_da_vitima,
    Religiao_da_vitima,
    Raca_Cor_da_vitima,
    Etnia_da_vitima,
    Faixa_de_renda_da_vitima,
    Natureza_Juridica_do_Suspeito,
    Sexo_do_suspeito,
    Orientacao_sexual_do_suspeito,
    Faixa_etaria_do_suspeito,
    Suspeito_nacionalidade,
    sl_suspeito_naturalidade,
    sl_suspeito_naturalizado_uf,
    sl_suspeito_naturalizado_municipio,
    Deficiencia_do_suspeito,
    Doenca_rara_do_suspeito,
    Deficiencia_relacionada_a_doenca_rara_suspeito,
    Suspeito_preso,
    Pais_do_suspeito,
    UF_do_suspeito,
    sl_suspeito_municipio,
    Profissao_do_suspeito,
    Grau_de_instrucao_do_suspeito,
    Religiao_do_suspeito,
    Raca_Cor_do_suspeito,
    Suspeito_Etnia,
    Faixa_de_renda_do_suspeito,
    Vinculo_Orgao_PJ_do_suspeito,
    sl_suspeito_ramo,
    suspeito_especificacao_etnia,
    vitima_especificacao_etnia,
    violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_S2_2022 ),
  ligue180_t1_2023 AS (
  SELECT
    Data_de_cadastro,
    Canal_de_atendimento,
    Denuncia_emergencial,
    Denunciante,
    Cenario_da_violacao,
    Pais,
    UF,
    Municipio,
    Frequencia,
    Inicio_das_violacoes,
    sl_quantidade_vitimas,
    Grupo_vulneravel,
    Motivacao,
    Relacao_vitima_suspeito,
    sl_vitima_cadastro,
    Sexo_da_vitima,
    Orientacao_sexual_da_vitima,
    Faixa_etaria_da_vitima,
    Nacionalidade_da_vitima,
    sl_vitima_naturalidade,
    sl_vitima_naturalizado_uf,
    sl_vitima_naturalizado_municipio,
    Deficiencia_da_vitima,
    Doenca_rara_da_vitima,
    Deficiencia_relacionada_a_doenca_rara,
    Vitima_preso_a,
    Pais_da_vitima,
    UF_da_vitima,
    Municipio_da_vitima,
    Profissao_da_vitima,
    Grau_de_instrucao_da_vitima,
    Religiao_da_vitima,
    Raca_Cor_da_vitima,
    Etnia_da_vitima,
    Faixa_de_renda_da_vitima,
    Natureza_Juridica_do_Suspeito,
    Sexo_do_suspeito,
    Orientacao_sexual_do_suspeito,
    Faixa_etaria_do_suspeito,
    Suspeito_nacionalidade,
    sl_suspeito_naturalidade,
    sl_suspeito_naturalizado_uf,
    sl_suspeito_naturalizado_municipio,
    Deficiencia_do_suspeito,
    Doenca_rara_do_suspeito,
    Deficiencia_relacionada_a_doenca_rara_suspeito,
    Suspeito_preso,
    Pais_do_suspeito,
    UF_do_suspeito,
    sl_suspeito_municipio,
    Profissao_do_suspeito,
    Grau_de_instrucao_do_suspeito,
    Religiao_do_suspeito,
    Raca_Cor_do_suspeito,
    Suspeito_Etnia,
    Faixa_de_renda_do_suspeito,
    Vinculo_Orgao_PJ_do_suspeito,
    sl_suspeito_ramo,
    suspeito_especificacao_etnia,
    vitima_especificacao_etnia,
    violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_T1_2023 ),
  ligue180_2019 AS (
  SELECT
    data_atendimento AS Datadecadastro,
    tipo_atendimento AS Canaldeatendimento,
    CAST(NULL AS STRING) AS Denunciaemergencial,
    CAST(NULL AS STRING) AS Denunciante,
    cenario_local AS Cenariodaviolacao,
    CAST(NULL AS STRING) AS Pais,
    CAST(NULL AS STRING) AS UF,
    CAST(NULL AS STRING) AS Municipio,
    cenario_ocorrencia AS Frequencia,
    CAST(NULL AS STRING) AS Iniciodasviolacoes,
    CAST(NULL AS STRING) AS sl_quantidade_vitimas,
    sub_grupo_violacao AS Grupovulneravel,
    CAST(NULL AS STRING) AS Motivacao,
    relacao_suspeito AS Relacaovitimasuspeito,
    CAST(NULL AS STRING) AS sl_vitima_cadastro,
    vitima_sexo AS Sexodavitima,
    vitima_identidade_genero AS Orientacaosexualdavitima,
    vitima_faixa_etaria AS Faixaetariadavitima,
    CAST(NULL AS STRING) AS Nacionalidadedavitima,
    CAST(NULL AS STRING) AS sl_vitima_naturalidade,
    CAST(NULL AS STRING) AS sl_vitima_naturalizado_uf,
    CAST(NULL AS STRING) AS sl_vitima_naturalizado_municipio,
    CAST(NULL AS STRING) AS Deficienciadavitima,
    CAST(NULL AS STRING) AS Doencararadavitima,
    CAST(NULL AS STRING) AS Deficienciarelacionadaadoencarara,
    CAST(NULL AS STRING) AS Vitimapresoa,
    CAST(NULL AS STRING) AS Paisdavitima,
    vitima_uf AS UFdavitima,
    vitima_municipio AS Municipiodavitima,
    CAST(NULL AS STRING) AS Profissaodavitima,
    vitima_escolaridade AS Graudeinstrucaodavitima,
    CAST(NULL AS STRING) AS Religiaodavitima,
    vitima_cor_raca AS RacaCordavitima,
    CAST(NULL AS STRING) AS Etniadavitima,
    CAST(NULL AS STRING) AS Faixaderendadavitima,
    CAST(NULL AS STRING) AS NaturezaJuridicadoSuspeito,
    suspeito_pf_sexo AS Sexodosuspeito,
    suspeito_pf_identidade_genero AS Orientacaosexualdosuspeito,
    suspeito_pf_faixa_etaria AS Faixaetariadosuspeito,
    CAST(NULL AS STRING) AS Suspeitonacionalidade,
    CAST(NULL AS STRING) AS sl_suspeito_naturalidade,
    CAST(NULL AS STRING) AS sl_suspeito_naturalizado_uf,
    CAST(NULL AS STRING) AS sl_suspeito_naturalizado_municipio,
    CAST(NULL AS STRING) AS Deficienciadosuspeito,
    CAST(NULL AS STRING) AS Doencararadosuspeito,
    CAST(NULL AS STRING) AS Deficienciarelacionadaadoencararasuspeito,
    CAST(NULL AS STRING) AS Suspeitopreso,
    CAST(NULL AS STRING) AS Paisdosuspeito,
    suspeito_pf_uf AS UFdosuspeito,
    suspeito_pf_municipio AS sl_suspeito_municipio,
    CAST(NULL AS STRING) AS Profissaodosuspeito,
    suspeito_pf_escolaridade AS Graudeinstrucaodosuspeito,
    CAST(NULL AS STRING) AS Religiaodosuspeito,
    suspeito_pf_cor_raca AS RacaCordosuspeito,
    CAST(NULL AS STRING) AS SuspeitoEtnia,
    CAST(NULL AS STRING) AS Faixaderendadosuspeito,
    CAST(NULL AS STRING) AS VinculoOrgaoPJdosuspeito,
    CAST(NULL AS STRING) AS sl_suspeito_ramo,
    CAST(NULL AS STRING) AS suspeito_especificacao_etnia,
    CAST(NULL AS STRING) AS vitima_especificacao_etnia,
    violacoes AS violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_2019 ),
  ligue180_s1_2020 AS (
  SELECT
    Datadadenuncia AS Datadecadastro,
    Canaldeatendimento,
    Denunciaemergencial,
    Denunciante,
    Cenariodaviolacao,
    Paisdeorigemdavitima AS Pais,
    UF,
    Municipio,
    CAST(NULL AS STRING) AS Frequencia,
    CAST(NULL AS STRING) AS Iniciodasviolacoes,
    CAST(NULL AS STRING) AS sl_quantidade_vitimas,
    Grupovulneravel,
    motivacoes AS Motivacao,
    RelacaoSuspeitoxVitima AS Relacaovitimasuspeito,
    CAST(NULL AS STRING) AS sl_vitima_cadastro,
    Sexodavitima,
    CAST(NULL AS STRING) AS Orientacaosexualdavitima,
    idade_vitima AS Faixaetariadavitima,
    Nacionalidadedavitima,
    CAST(NULL AS STRING) AS sl_vitima_naturalidade,
    CAST(NULL AS STRING) AS sl_vitima_naturalizado_uf,
    CAST(NULL AS STRING) AS sl_vitima_naturalizado_municipio,
    deficiencia_vitima AS Deficienciadavitima,
    CAST(NULL AS STRING) AS Doencararadavitima,
    CAST(NULL AS STRING) AS Deficienciarelacionadaadoencarara,
    CAST(NULL AS STRING) AS Vitimapresoa,
    Paisdeorigemdavitima AS Paisdavitima,
    CAST(NULL AS STRING) AS UFdavitima,
    CAST(NULL AS STRING) AS Municipiodavitima,
    CAST(NULL AS STRING) AS Profissaodavitima,
    Grauinstrucaodavitima AS Graudeinstrucaodavitima,
    CAST(NULL AS STRING) AS Religiaodavitima,
    Racacordavitima AS RacaCordavitima,
    Etniadavitima,
    Faixaderendadavitima,
    CAST(NULL AS STRING) AS NaturezaJuridicadoSuspeito,
    Sexodosuspeito,
    CAST(NULL AS STRING) AS Orientacaosexualdosuspeito,
    idade_suspeito AS Faixaetariadosuspeito,
    Nacionalidadedosuspeito AS Suspeitonacionalidade,
    CAST(NULL AS STRING) AS sl_suspeito_naturalidade,
    CAST(NULL AS STRING) AS sl_suspeito_naturalizado_uf,
    CAST(NULL AS STRING) AS sl_suspeito_naturalizado_municipio,
    deficiencia_suspeito AS Deficienciadosuspeito,
    CAST(NULL AS STRING) AS Doencararadosuspeito,
    CAST(NULL AS STRING) AS Deficienciarelacionadaadoencararasuspeito,
    CAST(NULL AS STRING) AS Suspeitopreso,
    Paisdeorigemdosuspeito AS Paisdosuspeito,
    CAST(NULL AS STRING) AS UFdosuspeito,
    CAST(NULL AS STRING) AS sl_suspeito_municipio,
    CAST(NULL AS STRING) AS Profissaodosuspeito,
    Grauinstrucaodosuspeito AS Graudeinstrucaodosuspeito,
    CAST(NULL AS STRING) AS Religiaodosuspeito,
    Racacordosuspeito AS RacaCordosuspeito,
    Etniadosuspeito AS SuspeitoEtnia,
    Faixaderendadosuspeito,
    CAST(NULL AS STRING) AS VinculoOrgaoPJdosuspeito,
    CAST(NULL AS STRING) AS sl_suspeito_ramo,
    CAST(NULL AS STRING) AS suspeito_especificacao_etnia,
    CAST(NULL AS STRING) AS vitima_especificacao_etnia,
    violacoes AS violacao
  FROM
    tcc-project-thais.raw_files.raw_ligue180_S1_2020 ),
  NOVA_TABELA_LIGUE180_2019_A_2023T1 AS (
  SELECT
    *
  FROM
    ligue180_s2_2020
  UNION ALL
  SELECT
    *
  FROM
    ligue180_s1_2021
  UNION ALL
  SELECT
    *
  FROM
    ligue180_s2_2021
  UNION ALL
  SELECT
    *
  FROM
    ligue180_s1_2022
  UNION ALL
  SELECT
    *
  FROM
    ligue180_s2_2022
  UNION ALL
  SELECT
    *
  FROM
    ligue180_t1_2023
  UNION ALL
  SELECT
    *
  FROM
    ligue180_2019
  UNION ALL
  SELECT
    *
  FROM
    ligue180_s1_2020 )
SELECT
  *
FROM
  NOVA_TABELA_LIGUE180_2019_A_2023T1